### PR TITLE
Added the ability to specify the 'non-presence' of HTTP headers.

### LINKED ISSUE #7: Detect the non-presence of a HTTP header
Hello everyone, thanks for sharing ChopChop.

According to the [documentation](https://github.com/michelin/ChopChop#creating-a-new-check), there is no way to detect the lack of a HTTP header.

It can be a nice feature to detect the absence of some security headers like "Strict-Transport-Security" or "Content-Security-Policy".

### PR DESCRIPTION
**Pull request by PaulSec**
You can specify them using a configuration file like this: 

```yaml
---
insecure: false
plugins:
  - uri: "/foobar"
    checks:
      - name: strict transport security detection
        remediation: No Strict transport security has been declared, add one!
        description: Triggers if Strict Transport Policy has not been properly declared
        severity: "Low"
        no_headers:
          - "Strict-Transport-Security:max-age=500; includeSubDomains; preload"
```

Closes #7

### CODE REVIEW

**Comment by S0obi** [comment]
Hello @PaulSec, LGTM after testing.
Regarding the case, where a user wants to only detect the non presence of a header, without a specific value, he will have to set "header_name:". The colon seems not really intuitive, we should add that to the documentation to make it clear.

If the user provides the header name without colon :
``` bash
$ ./gochopchop scan -u https://github.com -c chopchop.yml
No vulnerabilities found.
panic: runtime error: index out of range [1] with length 1

goroutine 6 [running]:
gochopchop/pkg.ResponseAnalysis(0xc0000d6cf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00002c690, 0x23, ...)
	/Users/tsoubiran/Documents/tools/ChopChop/pkg/resp_analysis.go:91 +0x7c2
gochopchop/app.Scan.func1(0xc000269e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000272860, 0xc0002b3090, 0x1, 0x1, ...)
	/Users/tsoubiran/Documents/tools/ChopChop/app/scan.go:144 +0x5f4
created by gochopchop/app.Scan
	/Users/tsoubiran/Documents/tools/ChopChop/app/scan.go:104 +0x9b8
```

With the following config : 

``` yaml
insecure: false
plugins:
  - uri: "/"
    checks:
      - name: strict transport security detection
        remediation: No Strict transport security has been declared, add one!
        description: Triggers if Strict Transport Policy has not been properly declared
        severity: "Low"
        no_headers:
            - "Strict-Transport-Security"
```

Thanks for this PR.

**Comment by PaulSec** [comment]
Oh you're right.

I added a check if the header is found but no value has been specified. 

You can try it with your YAML configuration file as: 

```yaml
insecure: false
plugins:
  - uri: "/"
    checks:
      - name: strict transport security detection
        remediation: No Strict transport security has been declared, add one!
        description: Triggers if Strict Transport Policy has not been properly declared
        severity: "Low"
        no_headers:
            - "Strict-Transport-Security"
```

And I launched it this way: 

```bash
./gochopchop scan -u http://127.0.0.1:8000 --timeout 1 --csv --csv-file boo.csv -c policy.yml
```

**Comment by S0obi** [comment]
Even better, I think we can merge it 👍

**Comment by PaulSec** [comment]
Rock on!

**Pull request merged**
